apiVersion: v1
kind: Secret
metadata:
  name: exchange-secrets
  namespace: exchange
type: Opaque
# Values must be base64 encoded
# echo -n "your-value" | base64
data:
  # postgres connection string
  ConnectionStrings__Postgres: "SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9Y3J5cHRvZXhjaGFuZ2U7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9cGFzc3dvcmQ="
  # redis connection string  
  # ConnectionStrings__Redis: "cmVkaXM6NjM3OQ=="